recipes.remove(<flansmod:dwBrassDust>);
recipes.remove(<flansmod:gunBox.extractorBlock>);
recipes.remove(<flansmod:dwABTArmorBox>);
recipes.remove(<flansmod:dwCarbonKnife>);
recipes.remove(<weather2:WeatherMachine>);
recipes.remove(<nnn:NetherGate>);
recipes.remove(<minecraft:gunpowder>);
recipes.remove(<flansmod:dwAssaultBoots>);
recipes.remove(<flansmod:dwAssaultBody>);
recipes.remove(<flansmod:flansWorkbench>);
recipes.remove(<minecraft:dirt:2>);
recipes.remove(<enviromine:camelPack>);
recipes.remove(<openmodularturrets:hardWallTierFive>);
recipes.remove(<openmodularturrets:hardWallTierFour>);
recipes.remove(<openmodularturrets:hardWallTierThree>);
recipes.remove(<openmodularturrets:hardWallTierTwo>);
recipes.remove(<openmodularturrets:hardWallTierOne>);
recipes.remove(<flansmod:dwWingbreakerPonyBoots>);
recipes.remove(<flansmod:dwWingbreakerPonyLegs>);
recipes.remove(<flansmod:dwWingbreakerPonyBody>);
recipes.remove(<flansmod:dwWingbreakerPonyHead>);
recipes.remove(<flansmod:dwWingbreakerBoots>);
recipes.remove(<flansmod:dwWingbreakerLegs>);
recipes.remove(<flansmod:dwWingbreakerBody>);
recipes.remove(<flansmod:dwWingbreakerHead>);
recipes.remove(<weather2:TornadoSensor>);
recipes.remove(<weather2:TornadoSiren>);
recipes.remove(<NuclearCraft:material:7>);
recipes.remove(<NuclearCraft:material:22>);
recipes.remove(<minecraft:slime_ball>);
recipes.remove(<enviromine:freezer>);
recipes.remove(<enviromine:elevator>);
recipes.remove(<enviromine:elevator:1>);
recipes.remove(<enviromine:airFilter>);
recipes.remove(<enviromine:esky>);
recipes.remove(<flansmod:dwGasMask>);
recipes.remove(<enviromine:gasMask>);
recipes.remove(<weather2:WeatherDeflector>);
recipes.remove(<powersuits:tile.tinkerTable>);
recipes.remove(<powersuits:item.powerFist>);
recipes.remove(<powersuits:item.powerArmorBoots>);
recipes.remove(<powersuits:item.powerArmorLeggings>);
recipes.remove(<powersuits:item.powerArmorChestplate>);
recipes.remove(<powersuits:item.powerArmorHelmet>);
recipes.remove(<MineFactoryReloaded:safarinet.jailer.fancy>);
recipes.remove(<MineFactoryReloaded:safarinet.jailer>);

<ezwastelands:ezwastelandblock>.displayName = "Dried Dirt";
<flansmod:gunBox.ambirconTechnologies>.addTooltip(format.yellow("Used for crafting guns and other weapon related stuff"));
<flansmod:gunBox.lupineMilitary>.addTooltip(format.yellow("Used for crafting guns and other weapon related stuff"));
<flansmod:gunBox.penbarUrbanPolice>.addTooltip(format.yellow("Used for crafting guns and other weapon related stuff"));
<flansmod:gunBox.skymareCorporation>.addTooltip(format.yellow("Used for crafting guns and other weapon related stuff"));
<flansmod:flansWorkbench:1>.addTooltip(format.yellow("Used for customizing your weapon of choice"));
<flansmod:gunBox.dwMiscBox>.addTooltip(format.yellow("Used for creating upgrades for your weapons"));
<nnn:NetherGate>.addTooltip(format.yellow("Used to craft all the nether related items"));
<flansmod:gunBox.extractorBlock>.displayName = "Extractor";
<flansmod:dwBrassDust>.displayName = "Copper and Iron Mix";
<minecraft:bone>.addTooltip(format.yellow("Can be found by mining bone piles"));
<minecraft:skull>.addTooltip(format.yellow("Can be found by mining bone piles"));
<minecraft:spawn_egg:90>.addTooltip(format.yellow("Craftable"));
<minecraft:spawn_egg:92>.addTooltip(format.yellow("Craftable"));
<minecraft:spawn_egg:93>.addTooltip(format.yellow("Craftable"));
<minecraft:spawn_egg:91>.addTooltip(format.yellow("Craftable"));
<NuclearCraft:pistol>.displayName = "Uranium Powered Gun";
<NuclearCraft:blockOre:4>.displayName = "Uranium Ore";
<BuildCraft|Silicon:laserBlock>.displayName = "Laser Coil";
<minecraft:spawn_egg:94>.addTooltip(format.yellow("Craftable"));
<minecraft:spawn_egg:95>.addTooltip(format.yellow("Craftable"));
<minecraft:spawn_egg:96>.addTooltip(format.yellow("Craftable"));
<minecraft:spawn_egg:98>.addTooltip(format.yellow("Craftable"));
<minecraft:spawn_egg:100>.addTooltip(format.yellow("Craftable"));
<flansmod:dwZincPellets>.displayName = "Magnesium Pellets";
<minecraft:skull:2>.displayName = "Ghoul Head";
<MineFactoryReloaded:syringe.zombie>.displayName = "Ghoul Syringe";
<MineFactoryReloaded:syringe.cure>.displayName = "De-Ghoulifycation Syringe";
<enviromine:camelPack>.anyDamage().addTooltip(format.darkAqua("Refills your water bar without the need to drink"));

var camelpack = <enviromine:camelPack>.anyDamage();

recipes.addShapeless(<minecraft:grass>, [<minecraft:wheat_seeds>, <minecraft:dirt>]);
recipes.addShapeless(<minecraft:dirt>, [<minecraft:water_bucket>, <ezwastelands:ezwastelandblock>]);
recipes.addShapeless(<minecraft:dirt:2>, [<minecraft:wheat_seeds>, <minecraft:grass>]);
recipes.addShapeless(<minecraft:string> * 6, [<minecraft:shears>.giveBack(<minecraft:shears>), <minecraft:leather>]);
recipes.addShapeless(<enviromine:camelPack>.withTag({camelPackFill: 100, camelPackMax: 100, camelPath: "enviromine:camelPack", isCamelPack: 1 as byte}), [camelpack, <minecraft:water_bucket>.giveBack(<minecraft:bucket>)]);
recipes.addShapeless(<flansmod:dwZincPellets> * 4, [<ThermalFoundation:tool.pickaxePlatinum>.transformDamage(75), <NuclearCraft:material:50>]);
recipes.addShapeless(<flansmod:dwCopperPellets> * 4, [<ThermalFoundation:tool.pickaxePlatinum>.transformDamage(75), <ThermalFoundation:material:64>]);

recipes.addShaped(<minecraft:spawn_egg:100>, [[<ThermalExpansion:material:517>, <minecraft:spawn_egg:98>, <ThermalExpansion:material:517>], [<minecraft:spawn_egg:95>, <ThermalExpansion:material:517>, <minecraft:spawn_egg:95>], [<ThermalExpansion:material:517>, <minecraft:spawn_egg:98>, <ThermalExpansion:material:517>]]);
recipes.addShaped(<minecraft:spawn_egg:98>, [[<minecraft:fish>, <ThermalExpansion:material:517>, <minecraft:fish>], [<ThermalExpansion:material:517>, <minecraft:egg>, <ThermalExpansion:material:517>], [<minecraft:fish>, <ThermalExpansion:material:517>, <minecraft:fish>]]);
recipes.addShaped(<minecraft:spawn_egg:96>, [[<minecraft:brown_mushroom>, <minecraft:red_mushroom>, <minecraft:brown_mushroom>], [<minecraft:red_mushroom>, <minecraft:spawn_egg:92>, <minecraft:red_mushroom>], [<minecraft:brown_mushroom>, <minecraft:red_mushroom>, <minecraft:brown_mushroom>]]);
recipes.addShaped(<minecraft:spawn_egg:95>, [[<ThermalExpansion:Rockwool>, <minecraft:bone>, <ThermalExpansion:Rockwool>], [<minecraft:bone>, <minecraft:egg>, <minecraft:bone>], [<ThermalExpansion:Rockwool>, <minecraft:bone>, <ThermalExpansion:Rockwool>]]);
recipes.addShaped(<minecraft:spawn_egg:94>, [[<MineFactoryReloaded:stone:10>, <MineFactoryReloaded:ceramicdye:11>, <MineFactoryReloaded:stone:10>], [<MineFactoryReloaded:ceramicdye:11>, <minecraft:egg>, <MineFactoryReloaded:ceramicdye:11>], [<MineFactoryReloaded:stone:10>, <MineFactoryReloaded:ceramicdye:11>, <MineFactoryReloaded:stone:10>]]);
recipes.addShaped(<MineFactoryReloaded:machine.1:14>, [[<MineFactoryReloaded:plastic.sheet>, <minecraft:flint_and_steel>, <MineFactoryReloaded:plastic.sheet>], [<minecraft:brick_block>, <ThermalExpansion:Frame:1>, <minecraft:brick_block>], [<minecraft:brick_block>, <ThermalExpansion:material:2>, <minecraft:brick_block>]]);
recipes.addShaped(<flansmod:dwBrassDust>, [[<ore:dustIron>, <ThermalFoundation:material:32>], [<ThermalFoundation:material:32>, <ore:dustIron>]]);
recipes.addShaped(<minecraft:spider_eye>, [[<ore:dyeBlack>, <ore:dyeRed>], [<ore:stickWood>, <ore:dyeBlack>]]);
recipes.addShaped(<minecraft:reeds>, [[null, <minecraft:stick>, <ore:fertilizerOrganic>], [<minecraft:stick>, <ore:fertilizerOrganic>, <minecraft:stick>], [<ore:fertilizerOrganic>, <minecraft:stick>, null]]);
recipes.addShaped(<minecraft:dye>, [[<minecraft:flint>], [<ore:coal>], [<minecraft:water_bucket>]]);
recipes.addShaped(<minecraft:leather>, [[null, <minecraft:water_bucket>, null], [<minecraft:dye:15>, <minecraft:rotten_flesh>, <minecraft:dye:15>]]);
recipes.addShaped(<minecraft:gunpowder>, [[<minecraft:cobblestone>, <minecraft:dye:8>, <minecraft:cobblestone>], [<minecraft:dye:8>, <minecraft:redstone>, <minecraft:dye:8>], [<minecraft:cobblestone>, <minecraft:dye:8>, <minecraft:cobblestone>]]);
recipes.addShaped(<minecraft:ender_pearl>, [[null, <flansmod:dwElectricDust>, null], [<flansmod:dwElectricDust>, <minecraft:snowball>, <flansmod:dwElectricDust>], [null, <flansmod:dwElectricDust>, null]]);
recipes.addShaped(<minecraft:snowball>, [[null, <minecraft:dye:15>, null], [<minecraft:dye:15>, <minecraft:slime_ball>, <minecraft:dye:15>], [null, <minecraft:dye:15>, null]]);
recipes.addShaped(<ThermalFoundation:material:1026>, [[null, <minecraft:glowstone_dust>, <minecraft:glowstone_dust>], [<minecraft:glowstone_dust>, <minecraft:blaze_rod>, <minecraft:glowstone_dust>], [<minecraft:glowstone_dust>, <minecraft:glowstone_dust>, null]]);
recipes.addShaped(<ThermalFoundation:material:1028>, [[null, <ThermalFoundation:material:2>, <ThermalFoundation:material:2>], [<ThermalFoundation:material:2>, <minecraft:blaze_rod>, <ThermalFoundation:material:2>], [<ThermalFoundation:material:2>, <ThermalFoundation:material:2>, null]]);
recipes.addShaped(<ThermalFoundation:material:1024>, [[null, <minecraft:snowball>, <minecraft:snowball>], [<minecraft:snowball>, <minecraft:blaze_rod>, <minecraft:snowball>], [<minecraft:snowball>, <minecraft:snowball>, null]]);
recipes.addShaped(<minecraft:cactus>, [[<ThermalExpansion:material:516>, <minecraft:wheat_seeds>, <ThermalExpansion:material:516>], [<minecraft:wheat_seeds>, <minecraft:sand>, <minecraft:wheat_seeds>], [<ThermalExpansion:material:516>, <minecraft:wheat_seeds>, <ThermalExpansion:material:516>]]);
recipes.addShaped(<minecraft:spawn_egg:91>, [[<minecraft:bone>, <ore:fertilizerRich>, <minecraft:bone>], [<minecraft:wool>, <minecraft:egg>, <minecraft:wool>], [<minecraft:bone>, <ThermalExpansion:material:517>, <minecraft:bone>]]);
recipes.addShaped(<minecraft:spawn_egg:93>, [[null, <minecraft:chicken>, null], [<minecraft:chicken>, <minecraft:egg>, <minecraft:chicken>], [null, <minecraft:chicken>, null]]);
recipes.addShaped(<minecraft:spawn_egg:92>, [[<minecraft:leather>, <minecraft:beef>, <minecraft:leather>], [<minecraft:beef>, <minecraft:egg>, <minecraft:beef>], [<minecraft:leather>, <minecraft:beef>, <minecraft:leather>]]);
recipes.addShaped(<minecraft:spawn_egg:90>, [[null, <minecraft:porkchop>, null], [<minecraft:porkchop>, <minecraft:egg>, <minecraft:porkchop>], [null, <minecraft:porkchop>, null]]);
recipes.addShaped(<minecraft:chicken>, [[<minecraft:bone>, <ore:dyeWhite>, <minecraft:bone>], [<ore:fertilizerRich>, <minecraft:rotten_flesh>, <ore:fertilizerRich>], [<minecraft:bone>, <ore:dyeWhite>, <minecraft:bone>]]);
recipes.addShaped(<minecraft:beef>, [[<minecraft:bone>, <ore:dyeRed>, <minecraft:bone>], [<ThermalExpansion:material:517>, <minecraft:rotten_flesh>, <ThermalExpansion:material:517>], [<minecraft:bone>, <ore:dyeRed>, <minecraft:bone>]]);
recipes.addShaped(<minecraft:porkchop>, [[<minecraft:bone>, <ore:dyePink>, <minecraft:bone>], [<ThermalExpansion:material:517>, <minecraft:rotten_flesh>, <ThermalExpansion:material:517>], [<minecraft:bone>, <ore:dyePink>, <minecraft:bone>]]);
recipes.addShaped(<weather2:Anemometer>, [[<ThermalFoundation:material:64>, null, <ThermalFoundation:material:64>], [<minecraft:redstone>, <ThermalFoundation:material:64>, <minecraft:redstone>], [<ThermalFoundation:material:64>, null, <ThermalFoundation:material:64>]]);
recipes.addShaped(<weather2:TornadoSiren>, [[<minecraft:obsidian>, <OpenComputers:item:32>, <minecraft:obsidian>], [<ore:thermalexpansion:machineSignalum>, <minecraft:noteblock>, <ore:thermalexpansion:machineSignalum>], [<minecraft:obsidian>, <OpenComputers:motionSensor>, <minecraft:obsidian>]]);
recipes.addShaped(<openmodularturrets:serialPortAddon>, [[<minecraft:iron_ingot>, <minecraft:iron_ingot>, <minecraft:iron_ingot>], [<minecraft:iron_ingot>, <OpenComputers:case1>, <minecraft:iron_ingot>], [<minecraft:iron_ingot>, <minecraft:iron_ingot>, <minecraft:iron_ingot>]]);
recipes.addShaped(<minecraft:dye:3> * 3, [[<minecraft:hardened_clay>, <ThermalExpansion:material:516>, <minecraft:hardened_clay>], [<ThermalExpansion:material:516>, <ThermalExpansion:material:517>, <ThermalExpansion:material:516>], [<minecraft:hardened_clay>, <ThermalExpansion:material:516>, <minecraft:hardened_clay>]]);
recipes.addShaped(<minecraft:egg>, [[<MineFactoryReloaded:stone:1>, <MineFactoryReloaded:pinkslime>, <MineFactoryReloaded:stone:1>], [<MineFactoryReloaded:pinkslime>, <ThermalExpansion:material:517>, <MineFactoryReloaded:pinkslime>], [<MineFactoryReloaded:stone:1>, <MineFactoryReloaded:pinkslime>, <MineFactoryReloaded:stone:1>]]);
recipes.addShaped(<minecraft:web>, [[null, <minecraft:string>, null], [<minecraft:string>, <minecraft:slime_ball>, <minecraft:string>], [null, <minecraft:string>, null]]);
recipes.addShaped(<flansmod:dwSpinneret>, [[null, <flansmod:dwSteelIngot>, null], [<flansmod:dwSteelIngot>, <minecraft:web>, <flansmod:dwSteelIngot>], [null, <flansmod:dwSteelIngot>, null]]);
recipes.addShaped(<flansmod:dwPumpPart>, [[<flansmod:dwSteelIngot>, <flansmod:dwSteelIngot>, <flansmod:dwSteelIngot>], [null, <flansmod:dwSteelIngot>, null]]);
recipes.addShaped(<flansmod:dwPoisonRound> * 32, [[<minecraft:potion:16452>], [<minecraft:gunpowder>], [<flansmod:dwSteelIngot>]]);
recipes.addShaped(<flansmod:dwHighSteelIngot>, [[<flansmod:dwMidSteelIngot>, <ore:gemDiamond>, <flansmod:dwMidSteelIngot>], [<minecraft:diamond>, <ore:ingotTough>, <ore:gemDiamond>], [<flansmod:dwMidSteelIngot>, <ore:gemDiamond>, <flansmod:dwMidSteelIngot>]]);
recipes.addShaped(<NuclearCraft:material:7> * 25, [[<NuclearCraft:blockBlock:7>]]);
recipes.addShaped(<flansmod:gunBox.penbarUrbanPolice>, [[<ore:ingotIron>, <ore:ingotIron>, <ore:ingotIron>], [<minecraft:iron_bars>, <flansmod:dwBallisticGlass>, <minecraft:iron_bars>], [<flansmod:dwSteelIngot>, <flansmod:dwSteelIngot>, <flansmod:dwSteelIngot>]]);
recipes.addShaped(<weather2:WeatherDeflector>, [[<ore:ingotIron>, <ore:dustRedstone>, <ore:ingotIron>], [<weather2:TornadoSiren>, <ore:oc:circuitChip3>, <weather2:TornadoSiren>], [<ore:ingotIron>, <ore:dustRedstone>, <ore:ingotIron>]]);
recipes.addShaped(<powersuits:tile.tinkerTable>, [[<ore:gemEmerald>, <ore:componentLaserEmitter>, <ore:gemEmerald>], [null, <ThermalExpansion:Frame:2>, null], [<ore:ingotIron>, <ore:ingotTough>, <ore:ingotIron>]]);
recipes.addShaped(<powersuits:item.powerFist>, [[<NuclearCraft:material:7>, <ore:componentWiring>, <NuclearCraft:material:7>], [<ThermalFoundation:material:72>, <ThermalFoundation:material:71>, <ThermalFoundation:material:72>], [<powersuits:powerArmorComponent:1>, <ThermalFoundation:material:71>, <powersuits:powerArmorComponent:1>]]);
recipes.addShaped(<powersuits:item.powerArmorBoots>, [[<ore:ingotElectrum>, <ore:ingotElectrum>], [<powersuits:powerArmorComponent:1>, <powersuits:powerArmorComponent:1>], [<ThermalFoundation:material:72>, <ThermalFoundation:material:72>]]);
recipes.addShaped(<powersuits:item.powerArmorChestplate>, [[<ore:ingotElectrum>, null, <ore:ingotElectrum>], [<ore:ingotTough>, <ore:componentSolenoid>, <ore:ingotTough>], [<ore:ingotInvar>, <ore:ingotElectrum>, <ore:ingotInvar>]]);
recipes.addShaped(<powersuits:item.powerArmorLeggings>, [[<ore:ingotInvar>, <ore:ingotTough>, <ore:ingotInvar>], [<ore:ingotElectrum>, <ore:componentWiring>, <ore:ingotElectrum>], [<ThermalFoundation:material:72>, null, <ThermalFoundation:material:72>]]);
recipes.addShaped(<powersuits:item.powerArmorHelmet>, [[<ore:ingotInvar>, <ore:ingotTough>, <ore:ingotInvar>], [<ore:ingotElectrum>, <ore:componentWiring>, <ore:ingotElectrum>]]);
recipes.addShaped(<MineFactoryReloaded:safarinet.jailer.fancy>, [[<minecraft:golden_carrot>, <minecraft:golden_carrot>, <minecraft:golden_carrot>], [<minecraft:golden_carrot>, <MineFactoryReloaded:safarinet.jailer>, <minecraft:golden_carrot>], [<minecraft:golden_carrot>, <minecraft:golden_carrot>, <minecraft:golden_carrot>]]);
recipes.addShaped(<MineFactoryReloaded:safarinet.jailer>, [[<MineFactoryReloaded:safarinet.singleuse>, <minecraft:iron_bars>, <MineFactoryReloaded:safarinet.singleuse>], [<minecraft:iron_bars>, <minecraft:golden_apple>, <minecraft:iron_bars>], [<MineFactoryReloaded:safarinet.singleuse>, <minecraft:iron_bars>, <MineFactoryReloaded:safarinet.singleuse>]]);
recipes.addShaped(<minecraft:water_bucket>, [[<ThermalExpansion:material:516>], [<BuildCraft|Transport:pipeLens:33>], [<WLM:item.toxicWasteBucket>]]);
recipes.addShaped(<enviromine:camelPack>, [[<minecraft:leather>, <flansmod:dwPumpPart>, <minecraft:leather>], [<minecraft:leather>, <ThermalExpansion:Tank:1>, <minecraft:leather>], [<minecraft:leather>, <minecraft:leather>, <minecraft:leather>]]);
recipes.addShaped(<ThermalExpansion:material:515>, [[<flansmod:dwCopperPellets>, <ThermalExpansion:material:513>, <flansmod:dwZincPellets>], [<ThermalExpansion:material:514>, <ore:crystalCinnabar>, <ThermalExpansion:material:514>], [<flansmod:dwZincPellets>, <ThermalExpansion:material:513>, <flansmod:dwCopperPellets>]]);
recipes.addShaped(<ThermalExpansion:material:514>, [[<flansmod:dwCopperPellets>, <flansmod:dwZincPellets>, <flansmod:dwCopperPellets>], [<flansmod:dwZincPellets>, <ThermalExpansion:material:512>, <flansmod:dwZincPellets>], [<flansmod:dwCopperPellets>, <flansmod:dwZincPellets>, <flansmod:dwCopperPellets>]]);
recipes.addShaped(<openmodularturrets:hardWallTierFive> * 12, [[<ore:plateBasic>, <NuclearCraft:parts:9>, <ore:plateBasic>], [<NuclearCraft:parts:9>, <ore:plateBasic>, <NuclearCraft:parts:9>], [<ore:plateBasic>, <NuclearCraft:parts:9>, <ore:plateBasic>]]);
recipes.addShaped(<openmodularturrets:hardWallTierFour> * 12, [[<ore:plateBasic>, <NuclearCraft:parts:8>, <ore:plateBasic>], [<NuclearCraft:parts:8>, <ore:plateBasic>, <NuclearCraft:parts:8>], [<ore:plateBasic>, <NuclearCraft:parts:8>, <ore:plateBasic>]]);
recipes.addShaped(<openmodularturrets:hardWallTierThree> * 12, [[<ore:plateBasic>, <NuclearCraft:parts:3>, <ore:plateBasic>], [<NuclearCraft:parts:3>, <ore:plateBasic>, <NuclearCraft:parts:3>], [<ore:plateBasic>, <NuclearCraft:parts:3>, <ore:plateBasic>]]);
recipes.addShaped(<openmodularturrets:hardWallTierTwo> * 12, [[<ore:plateBasic>, <NuclearCraft:parts:1>, <ore:plateBasic>], [<NuclearCraft:parts:1>, <ore:plateBasic>, <NuclearCraft:parts:1>], [<ore:plateBasic>, <NuclearCraft:parts:1>, <ore:plateBasic>]]);
recipes.addShaped(<openmodularturrets:hardWallTierOne> * 12, [[<ore:plateBasic>, <ore:plateTin>, <ore:plateBasic>], [<ore:plateTin>, <ore:plateBasic>, <ore:plateTin>], [<ore:plateBasic>, <ore:plateTin>, <ore:plateBasic>]]);
recipes.addShaped(<NuclearCraft:material:7>, [[<ThermalFoundation:material:4>, <ThermalFoundation:material:4>, <ThermalFoundation:material:4>], [<ore:dustPyrotheum>, <ore:ingotIron>, <ore:dustCryotheum>], [<ThermalFoundation:material:4>, <ThermalFoundation:material:4>, <ThermalFoundation:material:4>]]);
recipes.addShaped(<minecraft:slime_ball>, [[<minecraft:dye:10>, <ThermalExpansion:material:516>, <minecraft:dye:10>], [<ThermalExpansion:material:516>, <minecraft:dye:10>, <ThermalExpansion:material:516>], [<minecraft:dye:10>, <ThermalExpansion:material:516>, <minecraft:dye:10>]]);
recipes.addShaped(<flansmod:dwValkyrieHead>, [[<minecraft:enchanted_book>.withTag({StoredEnchantments: [{lvl: 4 as short, id: 2 as short}]}), <flansmod:dwHighSteelIngot>, <minecraft:enchanted_book>.withTag({StoredEnchantments: [{lvl: 4 as short, id: 2 as short}]})], [<minecraft:potion:8226>, <flansmod:dwContractorHead>, <minecraft:potion:8226>], [<minecraft:enchanted_book>.withTag({StoredEnchantments: [{lvl: 4 as short, id: 2 as short}]}), <flansmod:dwHighSteelIngot>, <minecraft:enchanted_book>.withTag({StoredEnchantments: [{lvl: 4 as short, id: 2 as short}]})]]);
recipes.addShaped(<flansmod:dwValkyrieBody>, [[<flansmod:dwSkymareArmor>, <minecraft:potion:8226>, <flansmod:dwSkymareArmor>], [<flansmod:dwHighSteelIngot>, <flansmod:dwContractorBody>, <flansmod:dwHighSteelIngot>], [<flansmod:dwSkymareArmor>, <minecraft:potion:8226>, <flansmod:dwSkymareArmor>]]);
recipes.addShaped(<flansmod:dwValkyrieLegs>, [[<flansmod:dwSkymareArmor>, <minecraft:potion:8226>, <flansmod:dwSkymareArmor>], [<flansmod:dwHighSteelIngot>, <flansmod:dwContractorLegs>, <flansmod:dwHighSteelIngot>], [<flansmod:dwSkymareArmor>, <minecraft:potion:8226>, <flansmod:dwSkymareArmor>]]);
recipes.addShaped(<flansmod:dwValkyrieBoots>, [[<flansmod:dwSkymareArmor>, <minecraft:potion:8194>, <flansmod:dwSkymareArmor>], [<flansmod:dwHighSteelIngot>, <flansmod:dwContractorBoots>, <flansmod:dwHighSteelIngot>], [<flansmod:dwSkymareArmor>, <minecraft:potion:8194>, <flansmod:dwSkymareArmor>]]);
recipes.addShaped(<flansmod:dwContractorHead>, [[<ThermalExpansion:Glass>, <flansmod:dwSkymareArmor>, <ThermalExpansion:Glass>], [<flansmod:dwSkymareArmor>, null, <flansmod:dwSkymareArmor>]]);
recipes.addShaped(<flansmod:dwContractorBody>, [[<flansmod:dwSkymareArmor>, null, <flansmod:dwSkymareArmor>], [<flansmod:dwSkymareArmor>, <flansmod:dwSkymareArmor>, <flansmod:dwSkymareArmor>], [<flansmod:dwSkymareArmor>, <flansmod:dwSkymareArmor>, <flansmod:dwSkymareArmor>]]);
recipes.addShaped(<flansmod:dwContractorLegs>, [[<flansmod:dwSkymareArmor>, <flansmod:dwSkymareArmor>, <flansmod:dwSkymareArmor>], [<flansmod:dwSkymareArmor>, null, <flansmod:dwSkymareArmor>], [<flansmod:dwSkymareArmor>, null, <flansmod:dwSkymareArmor>]]);
recipes.addShaped(<flansmod:dwContractorBoots>, [[<flansmod:dwSkymareArmor>, <flansmod:dwSkymareArmor>], [<flansmod:dwSkymareArmor>, <flansmod:dwSkymareArmor>]]);
recipes.addShaped(<flansmod:dwCasualBody>, [[<minecraft:leather>, <flansmod:dwKipliteArmor>, <minecraft:leather>], [<flansmod:dwKipliteArmor>, <flansmod:dwKipliteArmor>, <flansmod:dwKipliteArmor>], [null, <flansmod:dwKipliteArmor>, null]]);
recipes.addShaped(<flansmod:dwCasualLegs>, [[<minecraft:leather>, <flansmod:dwKipliteArmor>, <minecraft:leather>], [<flansmod:dwKipliteArmor>, null, <flansmod:dwKipliteArmor>], [<minecraft:leather>, null, <minecraft:leather>]]);
recipes.addShaped(<flansmod:dwTacticalBoots>, [[<flansmod:dwKipliteArmor>, <flansmod:dwMidSteelIngot>, <flansmod:dwKipliteArmor>], [<flansmod:dwMidSteelIngot>, <flansmod:dwAssaultBoots>, <flansmod:dwMidSteelIngot>], [<flansmod:dwKipliteArmor>, <flansmod:dwMidSteelIngot>, <flansmod:dwKipliteArmor>]]);
recipes.addShaped(<flansmod:dwTacticalLegs>, [[<flansmod:dwKipliteArmor>, <flansmod:dwMidSteelIngot>, <flansmod:dwKipliteArmor>], [<flansmod:dwMidSteelIngot>, <flansmod:dwAssaultLegs>, <flansmod:dwMidSteelIngot>], [<flansmod:dwKipliteArmor>, <flansmod:dwMidSteelIngot>, <flansmod:dwKipliteArmor>]]);
recipes.addShaped(<flansmod:dwTacticalBody>, [[<flansmod:dwKipliteArmor>, <flansmod:dwMidSteelIngot>, <flansmod:dwKipliteArmor>], [<flansmod:dwMidSteelIngot>, <flansmod:dwAssaultBody>, <flansmod:dwMidSteelIngot>], [<flansmod:dwKipliteArmor>, <flansmod:dwMidSteelIngot>, <flansmod:dwKipliteArmor>]]);
recipes.addShaped(<flansmod:dwTacticalHead>, [[<flansmod:dwKipliteArmor>, <flansmod:dwMidSteelIngot>, <flansmod:dwKipliteArmor>], [<minecraft:potion:8262>, <flansmod:dwAssaultHead>, <minecraft:potion:8262>], [<flansmod:dwKipliteArmor>, <flansmod:dwMidSteelIngot>, <flansmod:dwKipliteArmor>]]);
recipes.addShaped(<flansmod:dwAssaultHead>, [[<flansmod:dwMidSteelIngot>, <NuclearCraft:material:7>, <flansmod:dwMidSteelIngot>], [<flansmod:dwSteelIngot>, <MineFactoryReloaded:ceramicdye:12>, <flansmod:dwSteelIngot>]]);
recipes.addShaped(<flansmod:dwAssaultBody>, [[<flansmod:dwKipliteArmor>, <MineFactoryReloaded:ceramicdye:12>, <flansmod:dwKipliteArmor>], [<flansmod:dwMidSteelIngot>, <flansmod:dwMidSteelIngot>, <flansmod:dwMidSteelIngot>], [<flansmod:dwKipliteArmor>, <flansmod:dwMidSteelIngot>, <flansmod:dwKipliteArmor>]]);
recipes.addShaped(<flansmod:dwAssaultLegs>, [[<flansmod:dwMidSteelIngot>, <flansmod:dwMidSteelIngot>, <flansmod:dwMidSteelIngot>], [<flansmod:dwSteelIngot>, <ore:dyeCeramicBrown>, <flansmod:dwSteelIngot>], [<flansmod:dwSteelIngot>, <ore:dyeCeramicBrown>, <flansmod:dwSteelIngot>]]);
recipes.addShaped(<flansmod:dwAssaultBoots>, [[<flansmod:dwMidSteelIngot>, <flansmod:dwMidSteelIngot>], [<flansmod:dwKipliteArmor>, <flansmod:dwKipliteArmor>], [<ore:dyeCeramicBrown>, <ore:dyeCeramicBrown>]]);
recipes.addShaped(<flansmod:dwChamberlainBoots>, [[<flansmod:dwKipliteArmor>, <flansmod:dwKipliteArmor>, <flansmod:dwKipliteArmor>], [<flansmod:dwHighSteelIngot>, <flansmod:dwWingbreakerBoots>, <flansmod:dwHighSteelIngot>], [<flansmod:dwKipliteArmor>, <flansmod:dwKipliteArmor>, <flansmod:dwKipliteArmor>]]);
recipes.addShaped(<flansmod:dwChamberlainLegs>, [[<flansmod:dwKipliteArmor>, <flansmod:dwKipliteArmor>, <flansmod:dwKipliteArmor>], [<flansmod:dwHighSteelIngot>, <flansmod:dwWingbreakerLegs>, <flansmod:dwHighSteelIngot>], [<flansmod:dwKipliteArmor>, <flansmod:dwKipliteArmor>, <flansmod:dwKipliteArmor>]]);
recipes.addShaped(<flansmod:dwChamberlainBody>, [[<flansmod:dwKipliteArmor>, <flansmod:dwKipliteArmor>, <flansmod:dwKipliteArmor>], [<flansmod:dwHighSteelIngot>, <flansmod:dwWingbreakerBody>, <flansmod:dwHighSteelIngot>], [<flansmod:dwKipliteArmor>, <flansmod:dwKipliteArmor>, <flansmod:dwKipliteArmor>]]);
recipes.addShaped(<flansmod:dwChamberlainHead>, [[<flansmod:dwHighSteelIngot>, <flansmod:dwHighSteelIngot>, <flansmod:dwHighSteelIngot>], [<minecraft:dye:8>, <flansmod:dwRiotHelmet>, <minecraft:dye:8>], [<minecraft:dye:2>, <flansmod:dwGasMask>, <minecraft:dye:2>]]);
recipes.addShaped(<flansmod:dwRiotHelmet>, [[<flansmod:dwMidSteelIngot>, <flansmod:dwIngotBrass>, <flansmod:dwMidSteelIngot>], [<flansmod:dwSteelIngot>, <ore:blockGlassHardened>, <flansmod:dwSteelIngot>]]);
recipes.addShaped(<flansmod:dwWingbreakerBody>, [[<minecraft:leather>, <flansmod:dwKipliteArmor>, <minecraft:leather>], [<flansmod:dwIngotBrass>, <flansmod:dwKipliteArmor>, <flansmod:dwIngotBrass>], [<flansmod:dwKipliteArmor>, <flansmod:dwKipliteArmor>, <flansmod:dwKipliteArmor>]]);
recipes.addShaped(<flansmod:dwWingbreakerLegs>, [[<flansmod:dwKipliteArmor>, <flansmod:dwMidSteelIngot>, <flansmod:dwKipliteArmor>]]);
recipes.addShaped(<flansmod:dwWingbreakerBoots>, [[<flansmod:dwKipliteArmor>, <flansmod:dwKipliteArmor>], [<flansmod:dwIngotBrass>, <flansmod:dwIngotBrass>]]);
recipes.addShaped(<flansmod:dwWingbreakerHead>, [[<flansmod:dwIngotBrass>, null, <flansmod:dwIngotBrass>], [<minecraft:leather>, <flansmod:dwSunnyGear>, <minecraft:leather>], [<flansmod:dwIngotBrass>, null, <flansmod:dwIngotBrass>]]);
recipes.addShaped(<flansmod:dwSpikedHead>, [[null, <flansmod:dwBrassCog>, null], [<minecraft:iron_ingot>, <flansmod:dwRedwood>, <minecraft:iron_ingot>], [<flansmod:dwRedwood>, null, <flansmod:dwRedwood>]]);
recipes.addShaped(<flansmod:dwLupineArmorTactical>, [[<flansmod:dwKipliteArmor>, null, <flansmod:dwKipliteArmor>], [<flansmod:dwKipliteArmor>, <flansmod:dwMidSteelIngot>, <flansmod:dwKipliteArmor>], [<flansmod:dwKipliteArmor>, <flansmod:dwSteelIngot>, <flansmod:dwKipliteArmor>]]);
recipes.addShaped(<flansmod:dwLupineArmorStandardB>, [[<flansmod:dwKipliteArmor>, null, <flansmod:dwKipliteArmor>], [<flansmod:dwKipliteArmor>, <flansmod:dwMidSteelIngot>, <flansmod:dwKipliteArmor>], [<flansmod:dwKipliteArmor>, <flansmod:dwKipliteArmor>, <flansmod:dwKipliteArmor>]]);
recipes.addShaped(<flansmod:dwLupineArmorStandard>, [[<flansmod:dwKipliteArmor>, null, <flansmod:dwKipliteArmor>], [<flansmod:dwKipliteArmor>, <flansmod:dwSteelIngot>, <flansmod:dwKipliteArmor>], [<flansmod:dwKipliteArmor>, <flansmod:dwKipliteArmor>, <flansmod:dwKipliteArmor>]]);
recipes.addShaped(<flansmod:dwFrostweatherBody>, [[<ThermalExpansion:Rockwool:9>, <ThermalExpansion:Rockwool:9>, <ThermalExpansion:Rockwool:9>], [<ThermalExpansion:Rockwool:9>, <flansmod:dwContractorBody>, <ThermalExpansion:Rockwool:9>], [<ThermalExpansion:Rockwool:9>, <ThermalExpansion:Rockwool:9>, <ThermalExpansion:Rockwool:9>]]);
recipes.addShaped(<enviromine:airFilter>, [[<minecraft:iron_ingot>, <minecraft:wool>, <minecraft:iron_ingot>], [<minecraft:wool>, <BuildCraft|Transport:pipeLens:33>, <minecraft:wool>], [<minecraft:iron_ingot>, <minecraft:wool>, <minecraft:iron_ingot>]]);
recipes.addShaped(<flansmod:dwGasMask>, [[<flansmod:dwSteelIngot>, <flansmod:dwBallisticGlass>, <flansmod:dwSteelIngot>], [<flansmod:dwSteelIngot>, <flansmod:dwMidSteelIngot>, <flansmod:dwSteelIngot>], [<enviromine:airFilter>, <flansmod:dwMidSteelIngot>, <enviromine:airFilter>]]);
recipes.addShaped(<nnn:NetherGate>, [[<minecraft:obsidian>, <MineFactoryReloaded:brick:9>, <minecraft:obsidian>], [<minecraft:obsidian>, <minecraft:flint_and_steel>, <minecraft:obsidian>], [<minecraft:obsidian>, <MineFactoryReloaded:brick:9>, <minecraft:obsidian>]]);







